name: mmex
version: 1.3.4
summary: Money Manager Ex - simple to use financial management software
description: |
  Money Manager Ex (MMEX) is a free, open-source, cross-platform,
  easy-to-use personal finance software. It primarily helps organize
  one's finances and keeps track of where, when and how the money goes.
  MMEX includes all the basic features that 90% of users would want to
  see in a personal finance application. The design goals are to
  concentrate on simplicity and user friendliness - something one can
  use everyday.
icon: resources/mmex.svg
confinement: strict
grade: stable

apps:
  mmex:
    command: desktop-launch mmex
    desktop: share/applications/mmex.desktop
    plugs: [home, network, x11, opengl, pulseaudio, removable-media]

parts:
  config.guess:
    plugin: dump
    source: git://git.savannah.gnu.org/config.git
    source-type: git
    source-depth: 1
    organize:
      config.*: tmp/
    stage:
      - tmp/config.*
    override-prime: 'true'

  bakefile:
    after: [config.guess]
    plugin: autotools
    source: https://github.com/vslavik/bakefile/releases/download/v0.2.9/bakefile-0.2.9.tar.gz
    source-type: tar
    build-packages:
      - python2.7-dev
      - python-libxml2
    override-build: |
      cp -vf "${SNAPCRAFT_STAGE}"/tmp/config.* admin/
      snapcraftctl build
      ln -frs \
        "${SNAPCRAFT_PART_INSTALL}"/lib/bakefile/bakefile.py \
        "${SNAPCRAFT_PART_INSTALL}"/bin/bakefile
      ln -frs \
        "${SNAPCRAFT_PART_INSTALL}"/lib/bakefile/bakefile_gen.py \
        "${SNAPCRAFT_PART_INSTALL}"/bin/bakefile_gen
    stage:
      - share/*
      - bin/*
      - lib/*
    override-prime: 'true'

  mmex:
    plugin: autotools
    source: .
    override-build: |
      cd build/bakefiles
      bakefile_gen
      cd ../../auxd
      rm -f config.*
      bakefilize -c -v
      cd ..
      aclocal -I m4 -I $SNAPCRAFT_STAGE/share/aclocal
      autoconf
      snapcraftctl build
    after: [desktop-gtk2, bakefile]
    build-packages:
      - build-essential
      - gettext
      - libwxgtk-webview3.0-dev
    stage-packages:
      - libwxgtk-webview3.0-0v5
      - wx3.0-i18n
