FROM fedora:25
MAINTAINER developers@moneymanagerex.org

RUN yum -y update && yum -y install cmake gcc-c++ gettext git gtk3-devel make rpm-build webkitgtk3-devel wxGTK3-devel

# copy MMEX source code to the container:
ADD . /moneymanagerex

# Define working directory:
WORKDIR /moneymanagerex

CMD cmake . && make
