FROM ubuntu:xenial
MAINTAINER developers@moneymanagerex.org

RUN apt-get update && apt-get install -y cmake g++ git libgtk-3-dev libwebkitgtk-dev libwxgtk3.0-dev libwxgtk-webview3.0-dev make

# copy MMEX source code to the container:
ADD . /moneymanagerex

# Define working directory:
WORKDIR /moneymanagerex

CMD cmake . && make
