name: mmex
version: git
version-script: git describe --match 'v*' --tags --abbrev=0 | cut -c2-
summary: Money Manager Ex - simple to use financial management software
description: |
  Money Manager Ex (MMEX) is a free, open-source, cross-platform,
  easy-to-use personal finance software. It primarily helps organize
  one's finances and keeps track of where, when and how the money goes.
  MMEX includes all the basic features that 90% of users would want to
  see in a personal finance application. The design goals are to
  concentrate on simplicity and user friendliness - something one can
  use everyday.
icon: resources/mmex.svg
confinement: strict
grade: stable

apps:
  mmex:
    command: desktop-launch mmex
    desktop: share/applications/mmex.desktop
    plugs: [home, network, x11, opengl, pulseaudio, removable-media]

parts:
  mmex:
    plugin: cmake
    source: .
    source-type: git
    configflags: [-DCMAKE_BUILD_TYPE=Release]
    after: [desktop-gtk2]
    build-packages:
      - build-essential
      - gettext
      - git
      - pkg-config
      - lsb-release
      - ccache
      - libwxgtk-webview3.0-dev
      - liblua5.3-dev
      - libcurl4-openssl-dev
      - rapidjson-dev
    stage-packages:
      - libwxgtk-webview3.0-0v5
      - liblua5.3-0
      - libcurl3
      - wx3.0-i18n
