FROM ubuntu:xenial
MAINTAINER developers@moneymanagerex.org
RUN apt-get update && apt-get install -y --no-install-recommends cmake gettext g++ git libwebkitgtk-dev libwxgtk3.0-dev libwxgtk-webview3.0-dev make
