FROM debian:stretch-slim
MAINTAINER developers@moneymanagerex.org
RUN apt-get update && apt-get install -y --no-install-recommends cmake build-essential gettext git libwebkitgtk-dev libwxgtk3.0-dev libwxgtk-webview3.0-dev lsb-release
