/*******************************************************
 Copyright: (c) 2013-2026 Guan Lisheng (guanlisheng@gmail.com)
 Copyright: (c) 2017-2018 Stefano Giorgio (stef145g)
 Copyright: (c) 2022      Mark Whalley (mark@ipx.co.uk)
 Copyright: (c) 2026      George Ef (george.a.ef@gmail.com)

 The code in this file was previously generated by [sqlite2cpp.py]
 ********************************************************/

#pragma once

#include "_TableBase.h"
#include "base/mmCache.h"

template<typename TableType, typename DataType>
class TableFactory : public TableType
{
    static_assert(
        std::is_base_of<TableBase, TableType>::value,
        "TableType must derive from TableBase"
    );

public:
    using Table  = TableType;
    using Row    = typename Table::Row;
    using Col    = typename Row::Col;
    using COL_ID = typename Col::COL_ID;
    using Data   = DataType;

    // A container to hold a list of Data records for the table
    struct DataA : public std::vector<Data>
    {
        const wxString to_json() const;
    };

// -- state

protected:
    mmCache<int64, Data> m_cache;

// -- constructor

public:
    TableFactory<TableType, DataType>() : m_cache(mmCache<int64, Data>()) {}
    ~TableFactory<TableType, DataType>() { m_cache.reset(); }

// -- methods

public:
    // Methods starting with 'find_' bypass the cache; other methods use the cache.
    auto unsafe_get_idN_data_n(const int64 idN) -> Data*;
    auto get_idN_data_n(const int64 idN) -> const Data*;
    auto get_idN_data_n(wxLongLong_t idN) -> const Data* { return get_idN_data_n(int64(idN)); }
    auto add_data_n(Data& data) -> const Data*;
    bool add_data_a(DataA& data);
    auto unsafe_update_data_n(Data* data) -> Data*;
    auto update_data_n(Data& data) -> const Data*;
    auto unsafe_save_data_n(Data* data) -> const Data*;
    auto save_data_n(Data& data) -> const Data*;
    bool save_data_a(DataA& data);
    bool unsafe_remove_id(const int64 id);
    void preload_cache(int max_size = 1000);
    void reset_cache() { m_cache.reset(); }
    bool cache_empty() const { return m_cache.get_stat().max_size == 0; }
    auto stat_json() const -> const wxString;
    void debug_stat() const;

    template<typename... Args>
    auto find_data_a(const Args&... clause_args) -> DataA;
    auto find_data_a() -> DataA;
    template<typename... Args>
    auto find_id_a(const Args&... clause_args) -> std::vector<int64>;
    auto find_id_a() -> std::vector<int64>;
    template<typename... Args>
    auto find_count(const Args&... clause_args) -> std::size_t;
    auto find_count() -> std::size_t;

    template<typename V, typename ArgV, typename... Args>
    auto find_value(
        const ArgV& clause_value,
        const Args&... clause_args
    ) -> V;
    template<typename G, typename... Args>
    auto find_count_mGroup(
        const wxString& group,
        const Args&... clause_args
    ) -> std::map<G, std::size_t>;
    template<typename G, typename V, typename ArgV, typename... Args>
    auto find_value_mGroup(
        const wxString& group,
        const ArgV& clause_value,
        const Args&... clause_args
    ) -> std::map<G, V>;

    template<typename... Args>
    auto unsafe_search_cache_n(const Args& ... args) -> Data*;
    template<typename... Args>
    auto search_cache_n(const Args& ... args) -> const Data*;

// -- virtual

    // Check if id in this table is used by other records (in this or other tables).
    // id in this table cannot be deleted if it is used by other records.
    // Records fully owned by id are ignored (they can be deleted together with id).
    // If ignore_deleted is true, deleted transactions are also also ignored.
    // The complete list of table dependencies can be found in _dependencies.txt
    virtual auto find_id_isUsed([[maybe_unused]] int64 id, [[maybe_unused]] bool ignore_deleted = false) -> bool {
        return false;
    }

    // Remove all auxiliary records in other tables owned by id, and then
    // remove id from this table. Return false in case or error.
    // Before calling this function, the caller shall validate that only records fully
    // owned by id refer to it, i.e., no references to id remain after this call.
    // Specializations of this function shall stop immediately in case of error,
    // such that id in this table is removed only after all its auxiliary records
    // are removed (otherwise the database will contain dangling references).
    // The complete list of table dependencies can be found in _dependencies.txt
    virtual bool purge_id(int64 id) = 0;
};

// -- template methods

// Return the results of the following query:
//   SELECT * FROM ${TABLE} ${clause_args}
// clause_args may contain:
// * zero or more _WHERE clauses of the form
//   ${Table}Col::WHERE_${COLUMN}(op, value)
//   op can be omitted if it is equal to OP_EQ (the "equal" operator).
//   By default, _WHERE clauses are combined with an AND logical operator.
//   Composite conditions can be specified using nested _PAREN clauses:
//   TableClause::BEGIN_AND() .. TableClause::END() : combined with AND
//   TableClause::BEGIN_OR()  .. TableClause::END() : combined with OR
// * zero or more _ORDER clauses of the form
//   ${Table}Model::ORDERBY_${COLUMN}(${desc})
//   The order is descending if ${desc} is true.
//   The default value of ${desc} is false.
// * an optional _LIMIT clause or the form
//   TableClause::LIMIT(${limit}, ${offset})
//   The default value of ${offset} is 0.
template<typename T, typename D>
template<typename... Args>
auto TableFactory<T, D>::find_data_a(const Args&... clause_args) -> DataA
{
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );

    DataA result;
    try {
        wxString query;
        std::vector<int> index_a;
        this->select_query(query, index_a, clause_args...);
        //wxLogDebug("TableFactory::find_data_a: query: [%s]", query);

        wxSQLite3Statement stmt = this->m_db->PrepareStatement(query);
        this->bind_stmt(stmt, index_a, 0, clause_args...);
        wxSQLite3ResultSet q = stmt.ExecuteQuery();

        while (q.NextRow()) {
            Data r(q);
            result.push_back(std::move(r));
        }

        q.Finalize();
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("TableFactory::find_data_a: Table %s: Exception %s",
            this->m_table_name, e.GetMessage().utf8_str()
        );
    }

    return result;
}

template<typename T, typename D>
auto TableFactory<T, D>::find_data_a() -> DataA
{
    return find_data_a(TableClause::EMPTY());
}

// Return the results of the following query:
//   SELECT ${PRIMARY} FROM ${TABLE} ${clause_args}
// clause_args may contain _WHERE, _PAREN, _ORDER, _LIMIT clauses, as in find_data_a().
template<typename T, typename D>
template<typename... Args>
auto TableFactory<T, D>::find_id_a(const Args&... clause_args) -> std::vector<int64>
{
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );

    std::vector<int64> result;
    try {
        wxString query;
        std::vector<int> index_a;
        TableClauseD clause_id = TableClause::RESULT(Col::s_primary_name);
        this->select_query(query, index_a, clause_id, clause_args...);
        //wxLogDebug("TableFactory::find_id_a: query: [%s]", query);

        wxSQLite3Statement stmt = this->m_db->PrepareStatement(query);
        this->bind_stmt(stmt, index_a, 0, clause_id, clause_args...);
        wxSQLite3ResultSet q = stmt.ExecuteQuery();

        while (q.NextRow()) {
            int64 id = q.GetInt64(0);
            result.push_back(id);
        }

        q.Finalize();
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("TableFactory::find_id_a: Table %s: Exception %s",
            this->m_table_name, e.GetMessage().utf8_str()
        );
    }

    return result;
}

template<typename T, typename D>
auto TableFactory<T, D>::find_id_a() -> std::vector<int64>
{
    return find_id_a(TableClause::EMPTY());
}

// Return the results of the following query:
//   SELECT COUNT(*) FROM ${TABLE} ${clause_args}
// clause_args may contain _WHERE or _PAREN clauses.
template<typename T, typename D>
template<typename... Args>
auto TableFactory<T, D>::find_count(const Args&... clause_args) -> std::size_t
{
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );

    std::size_t result = 0;
    try {
        wxString query;
        std::vector<int> index_a;
        TableClauseD clause_count = TableClause::RESULT("COUNT(*)");
        this->select_query(query, index_a, clause_count, clause_args...);
        //wxLogDebug("TableFactory::find_count: query: [%s]", query);

        wxSQLite3Statement stmt = this->m_db->PrepareStatement(query);
        this->bind_stmt(stmt, index_a, 0, clause_count, clause_args...);
        wxSQLite3ResultSet q = stmt.ExecuteQuery();

        if (q.NextRow()) {
            result = static_cast<std::size_t>(q.GetInt64(0).GetValue());
        }

        q.Finalize();
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("TableFactory::find_count: Table %s: Exception %s",
            this->m_table_name, e.GetMessage().utf8_str()
        );
    }

    return result;
}

template<typename T, typename D>
auto TableFactory<T, D>::find_count() -> std::size_t
{
    return find_count(TableClause::EMPTY());
}

// Return the results of the following query:
//   SELECT ${AGGREGATE}(${COLUMN_V) FROM ${TABLE} ${clause_args}
// clause_value is an aggregate _RESULT clause of the form
//   ${Table}Model::${AGGREGATE}_${COLUMN_V}
// where ${AGGREGATE} is one of SUM, MIN, MAX.
// clause_args may contain _WHERE or _PAREN clauses.
template<typename T, typename D>
template<typename V, typename ArgV, typename... Args>
auto TableFactory<T, D>::find_value(
    const ArgV& clause_value,
    const Args&... clause_args
) -> V
{
    static_assert(
        std::is_base_of<TableClause, ArgV>::value,
        "ArgV must derive from TableClause"
    );
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );

    V result;
    if (clause_value.m_id != TableClause::CLAUSE_ID_RESULT) {
        wxLogError("TableFactory::find_value: the first argument must be _RESULT");
        return result;
    }

    try {
        wxString query;
        std::vector<int> index_a;
        this->select_query(query, index_a, clause_value, clause_args...);
        //wxLogDebug("TableFactory::find_value: query: [%s]", query);

        wxSQLite3Statement stmt = this->m_db->PrepareStatement(query);
        this->bind_stmt(stmt, index_a, 0, clause_value, clause_args...);
        wxSQLite3ResultSet q = stmt.ExecuteQuery();

        if (q.NextRow()) {
            TableBase::get_select_result(q, 0, result);
        }

        q.Finalize();
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("TableFactory::find_value: Table %s: Exception %s",
            this->m_table_name, e.GetMessage().utf8_str()
        );
    }

    return result;
}

// Return the results of the following query:
//   SELECT ${group}, COUNT(*) FROM ${TABLE}
//   ${clause_args}
//   GROUP BY ${group} ORDER BY ${group}
// as a map from ${group} to a count.
// group is the name of a column.
// clause_args may contain _WHERE or _PAREN clauses.
template<typename T, typename D>
template<typename G, typename... Args>
auto TableFactory<T, D>::find_count_mGroup(
    const wxString& group,
    const Args&... clause_args
) -> std::map<G, std::size_t>
{
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );

    std::map<G, std::size_t> result;
    try {
        wxString query;
        std::vector<int> index_a;
        TableClauseD clause_group = TableClause::RESULT(group);
        TableClauseD clause_count = TableClause::RESULT("COUNT(*)");
        this->select_query(query, index_a,
            clause_group, clause_count,
            clause_args...,
            TableClause::GROUPBY(group),
            TableClause::ORDERBY(group)
        );
        //wxLogDebug("TableFactory::find_count_mGroup: query: [%s]", query);

        wxSQLite3Statement stmt = this->m_db->PrepareStatement(query);
        this->bind_stmt(stmt, index_a, 0, clause_group, clause_count, clause_args...);
        wxSQLite3ResultSet q = stmt.ExecuteQuery();

        while (q.NextRow()) {
            G group1;
            TableBase::get_select_result(q, 0, group1);
            std::size_t count = static_cast<std::size_t>(q.GetInt64(1).GetValue());
            result.insert({group1, count});
        }

        q.Finalize();
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("TableFactory::find_count_mGroup: Table %s: Exception %s",
            this->m_table_name, e.GetMessage().utf8_str()
        );
    }

    return result;
}

// Return the results of the following query:
//   SELECT ${group}, ${AGGREGATE}(${COLUMN_V) FROM ${TABLE}
//   ${clause_args}
//   GROUP BY ${group} ORDER BY ${group}
// as a map from ${group} to an aggreagate value.
// group is the name of a column.
// clause_value is an aggregate _RESULT clause, as in find_value().
// clause_args may contain _WHERE or _PAREN clauses.
template<typename T, typename D>
template<typename G, typename V, typename ArgV, typename... Args>
auto TableFactory<T, D>::find_value_mGroup(
    const wxString& group,
    const ArgV& clause_value,
    const Args&... clause_args
) -> std::map<G, V>
{
    static_assert(
        std::is_base_of<TableClause, ArgV>::value,
        "ArgV must derive from TableClause"
    );
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );

    std::map<G, V> result;
    if (clause_value.m_id != TableClause::CLAUSE_ID_RESULT) {
        wxLogError("TableFactory::find_value_mGroup: the first argument must be _RESULT");
        return result;
    }

    try {
        wxString query;
        std::vector<int> index_a;
        TableClauseD clause_group = TableClause::RESULT(group);
        this->select_query(query, index_a,
            clause_group, clause_value,
            clause_args...,
            TableClause::GROUPBY(group),
            TableClause::ORDERBY(group)
        );
        //wxLogDebug("TableFactory::find_value_mGroup: query: [%s]", query);

        wxSQLite3Statement stmt = this->m_db->PrepareStatement(query);
        this->bind_stmt(stmt, index_a, 0, clause_group, clause_value, clause_args...);
        wxSQLite3ResultSet q = stmt.ExecuteQuery();

        while (q.NextRow()) {
            G group1;
            V value;
            TableBase::get_select_result(q, 0, group1);
            TableBase::get_select_result(q, 1, value);
            result.insert({group1, value});
        }

        q.Finalize();
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("TableFactory::find_value_mGroup: Table %s: Exception %s",
            this->m_table_name, e.GetMessage().utf8_str()
        );
    }

    return result;
}

// This is a trivial implementation of indexing in cache, using linear search.
// It does not require additional storage, other than the cache.
// TODO:
//   Implement a more efficient indexing using a map<key, id> for each key.
//   The index is used as a hint for fast access in cache. If the id is wrong,
//   the entry in the index is removed and a full search (with find) is executed.
template<typename T, typename D>
template<typename... Args>
auto TableFactory<T, D>::unsafe_search_cache_n(const Args& ... args) -> Data*
{
    for (auto& [_, r] : m_cache.get_map()) {
        if (r->id() > 0 && r->to_row().match(args...)) {
            return r;
        }
    }
    return nullptr;
}

template<typename T, typename D>
template<typename... Args>
auto TableFactory<T, D>::search_cache_n(const Args& ... args) -> const Data*
{
    return unsafe_search_cache_n(args...);
}
