/*******************************************************
Copyright (C) 2014, 2015 Nikolay

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*******************************************************/

#include <wx/imaglist.h>

enum img {
    HOUSE_PNG,
    SCHEDULE_PNG,
    CALENDAR_PNG,
    PIECHART_PNG,
    HELP_PNG,
    FILTER_PNG,
    ASSET_PNG,
    CRYPTO_PNG,
    CUSTOMSQL_PNG,
    CUSTOMSQL_GRP_PNG,
    SAVINGS_ACC_NORMAL_PNG,
    SAVINGS_ACC_FAVORITE_PNG,
    SAVINGS_ACC_CLOSED_PNG,
    CARD_ACC_PNG,
    CARD_ACC_FAVORITE_PNG,
    CARD_ACC_CLOSED_PNG,
    TERMACCOUNT_PNG,
    TERM_ACC_FAVORITE_PNG,
    TERM_ACC_CLOSED_PNG,
    STOCK_ACC_PNG,
    STOCK_ACC_FAVORITE_PNG,
    STOCK_ACC_CLOSED_PNG, 
    CASH_ACC_NORMAL_PNG,
    CASH_ACC_FAVORITE_PNG,
    CASH_ACC_CLOSED_PNG,
    LOAN_ACC_NORMAL_PNG,
    LOAN_ACC_FAVORITE_PNG,
    LOAN_ACC_CLOSED_PNG,
    CRYPTO_ACC_NORMAL_PNG,
    CRYPTO_ACC_FAVORITE_PNG,
    CRYPTO_ACC_CLOSED_PNG,
    LAST_NAVTREE_PNG
};

/* Images set for accounts to be user assigned */
enum acc_img {
    MONEY_DOLLAR_XPM = LAST_NAVTREE_PNG, //First user img
    MONEY_EURO_XPM,
    FLAG_XPM,
    COINS_XPM,
    ABOUT_XPM,
    CLOCK_XPM,
    CAT_XPM,
    DOG_XPM,
    TREES_XPM,
    HOURGLASS_XPM,
    WORK_XPM,
    PAYPAL_XPM,
    WALLET_XPM,
    RUBIK_CUBE_XPM,
    MAX_XPM,
};

enum png {
    NEW_DB,
    OPEN,
    SAVE,
    SAVEAS,
    APPSTART,
    CLEARLIST,
    DELETE_ACC,
    EDIT_ACC,
    REALLOCATE_ACC,
    ENCRYPT_DB,
    ENCRYPT_DB_EDIT,
    NEW_ACC,
    HOME,
    RELOCATION,
    CATEGORY,
    CATEGORY_RELOCATION,
    PAYEE,
    PAYEE_RELOCATION,
    MENU_RELOCATION,
    CURR,
    FILTER,
    GRM,
    CUSTOM,
    CLEAR,
    OPTIONS,
    NEW_TRX,
    LANG,
    ABOUT,
    HELP,
    COMMUNITY,
    GITHUB,
    SLACK,
    BUG,
    NEWS,
    NEW_NEWS,
    PP,
    FULLSCREEN,
    PIE_CHART,
    BUDGET,
    RECURRING,
    ASSET,
    CRYPTO,
    PROPERTY,
    CAR,
    HOUSEHOLD_OBJ,
    ART,
    JEWELLERY,
    CASH,
    OTHER,
    FACEBOOK,
    SAVINGS_NORMAL,
    SAVINGS_FAVORITES,
    SAVINGS_CLOSED,
    CC_NORMAL,
    CC_FAVORITE,
    CC_CLOSED,
    TERM_NORMAL,
    TERM_FAVORITE,
    TERM_CLOSED,
    STOCKS_NORMAL,
    STOCKS_FAVORITE,
    STOCKS_CLOSED,
    CASH_NORMAL,
    CASH_FAVORITE,
    CASH_CLOSED,
    LOAN_ACC_NORMAL,
    LOAN_ACC_FAVORITE,
    LOAN_ACC_CLOSED,
    CRYPTO_ACC_NORMAL,
    CRYPTO_ACC_FAVORITE,
    CRYPTO_ACC_CLOSED,
    RECONCILED,
    VOID_STAT,
    FOLLOW_UP,
    DUPLICATE_STAT,
	TRXNUM,
    RIGHTARROW,
    RIGHTARROW_ACTIVE,
    RIGHTARROWSIMPLE,
    LEFTARROWSIMPLE,
    GOOGLE_PLAY,
    UPDATE,
	CURRATES,
    FORUM,
    CLIP,
    PROFIT,
    LOSS,
    WEB,
    UPARROW,
    DOWNARROW,
    IMPORT,
    // LED_OFF,
    LED_RED,
    LED_YELLOW,
    LED_GREEN,
    RUN,
    AUTO,
    PRINT,
    EXIT,
    EMPTY,
};

wxImageList* navtree_images_list();
const wxBitmap mmBitmap(int ref);